# Generated by Django 2.1.7 on 2019-03-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AddField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default='', max_length=4096, verbose_name='Описание канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='key',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='Ключ канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL, verbose_name='Автор канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available channel'), (2, 'Deleted channel')], default=1, verbose_name='Статус канала'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики канала'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название канала'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='channel.Channel'),
        ),
    ]
