# Generated by Django 2.1.7 on 2019-03-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20190315_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='key',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Ключ канала'),
        ),
    ]
