# Generated by Django 2.1.7 on 2019-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20190315_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(default='', max_length=4096, verbose_name='Описание канала'),
        ),
    ]
