# Generated by Django 2.1.7 on 2019-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20190315_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='key',
            field=models.CharField(default=123456654321, max_length=12, verbose_name='Ключ плейлиста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='preview_picture',
            field=models.ImageField(null=True, upload_to='preview_playlist', verbose_name='Превью плейлиста'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available channel'), (1, 'Deleted channel')], default=0, verbose_name='Статус канала'),
        ),
    ]
