# Generated by Django 2.1.7 on 2019-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20190316_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Описание плeйлиста'),
        ),
    ]
