export const LOGIN_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';

// Centrifuge
export const CENTRIFUGO_INIT = 'CENTRIFUGO_INIT';
export const CENTRIFUGO_DTOR = 'CENTRIFUGO_DTOR';
export const SUBSCRIBE_TO_CHANNEL = 'SUBSCRIBE_TO_CHANNEL';
export const UNSUBSCRIBE_FROM_CHANNEL = 'UNSUBSCRIBE_FROM_CHANNEL';
export const ACTIVATE_SUBSCRIPTION = 'ACTIVATE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const OPENDRAWER = 'OPEN_DRAWER';
export const CLOSEDRAWER = 'CLOSE_DRAWER';
export const BUTTONCHOICE = 'BUTTON_CHOICE';

export const UPLOADFILE = 'UPLOAD_FILE';
export const ADD_CHANNEL = 'ADD_CHANNEL';

export const FETCH_HOT = 'FETCH_HOT';
export const FETCH_NEW = 'FETCH_NEW';
export const FETCH_SUBS = 'FETCH_SUBS';
export const FETCH_POP = 'FETCH_POP';
