# Generated by Django 2.1.7 on 2019-03-03 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название видео')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание видео')),
                ('preview_picture', models.ImageField(null=True, upload_to='preview_video', verbose_name='Превью видео')),
                ('mime', models.CharField(max_length=72, verbose_name='MIME-type видео')),
                ('key', models.CharField(max_length=72, verbose_name='ID видео')),
                ('content', models.FileField(upload_to='source_video', verbose_name='Видео')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL, verbose_name='Автор видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('id', 'name'),
            },
        ),
    ]
