# Generated by Django 2.1.7 on 2019-03-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='is_deleted',
        ),
    ]
