# Generated by Django 2.1.7 on 2019-03-04 21:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('video', '0002_remove_source_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название интерактивного видео')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание интерактивного видео')),
                ('preview_picture', models.ImageField(null=True, upload_to='preview_video', verbose_name='Превью интерактивного видео')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='channel.Channel', verbose_name='Канал видео')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='Название видео')),
                ('time', models.TimeField(verbose_name='Длительность видео')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='video.VideoPart', verbose_name='Часть видео')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_parts', to='video.Source', verbose_name='Источник видео')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='head_video_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.VideoPart', verbose_name='Стартовый фрагмент видео'),
        ),
    ]
