# Generated by Django 2.1.7 on 2019-03-04 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190304_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='key',
            field=models.CharField(default='', max_length=12, verbose_name='ID интерактивного видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopart',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
