# Generated by Django 2.1.7 on 2019-03-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_auto_20190304_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL, verbose_name='Автор видео'),
            preserve_default=False,
        ),
    ]
