# Generated by Django 2.1.7 on 2019-03-08 15:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20190306_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopart',
            name='main_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_parts', to='video.Video', verbose_name='Главное видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopart',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='video.VideoPart', verbose_name='Родительская часть видео'),
        ),
        migrations.AlterField(
            model_name='videopart',
            name='text',
            field=models.CharField(max_length=32, verbose_name='Текст к видео'),
        ),
    ]
