# Generated by Django 2.1.7 on 2019-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190308_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='codec',
            field=models.CharField(default='', max_length=32, verbose_name='Codec видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='key',
            field=models.CharField(max_length=32, verbose_name='ID видео'),
        ),
        migrations.AlterField(
            model_name='source',
            name='mime',
            field=models.CharField(max_length=32, verbose_name='MIME-type видео'),
        ),
        migrations.AlterField(
            model_name='source',
            name='time',
            field=models.FloatField(verbose_name='Длительность видео'),
        ),
    ]
