# Generated by Django 2.1.7 on 2019-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20190309_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(default='', max_length=32, verbose_name='Codec интерактивного видео'),
            preserve_default=False,
        ),
    ]
