# Generated by Django 2.1.7 on 2019-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_codec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='codec',
            field=models.CharField(default='undefined', max_length=32, verbose_name='Codec видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='codec',
            field=models.CharField(default='undefined', max_length=32, verbose_name='Codec интерактивного видео'),
        ),
    ]
