# Generated by Django 2.1.7 on 2019-03-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20190310_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='head_video_part',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.VideoPart', verbose_name='Стартовый фрагмент видео'),
        ),
    ]
