# Generated by Django 2.1.7 on 2019-03-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20190315_1639'),
        ('video', '0012_auto_20190310_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='channel.Playlist', verbose_name='Плейлист интерактивного видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published to channel'), (1, 'Hidden by user'), (2, 'Deleted')], default=0, verbose_name='Статус видео'),
        ),
    ]
