# Generated by Django 2.1.7 on 2019-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20190315_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='preview_picture',
            field=models.ImageField(null=True, upload_to='preview_source', verbose_name='Превью источника'),
        ),
    ]
