# Generated by Django 2.1.7 on 2019-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('video', '0014_auto_20190414_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='video', to='tag.Tag', verbose_name='Теги видео'),
        ),
    ]
