# Generated by Django 2.1.7 on 2019-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=16, verbose_name='Текст тега'),
        ),
    ]
