# Generated by Django 2.1.7 on 2019-03-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0013_auto_20190315_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(verbose_name='Счетчик просмотров')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='video.Video', verbose_name='Интерактивное видео')),
            ],
        ),
    ]
