# Generated by Django 2.1.7 on 2019-03-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='views',
            options={'verbose_name': 'Просмотры у интерактивного видео', 'verbose_name_plural': 'Просмотры у интерактивных видео'},
        ),
    ]
