# Generated by Django 2.1.7 on 2019-03-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0013_auto_20190315_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(verbose_name='Рейтинг интерактивного видео')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='video.Video', verbose_name='Интерактивное видео')),
            ],
            options={
                'verbose_name': 'Рейтинг интерактивного видео',
                'verbose_name_plural': 'Рейтинг интерактивных видео',
            },
        ),
        migrations.CreateModel(
            name='RatingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '+1 to rating'), (0, '+0 to rating'), (-1, '-1 to rating')], verbose_name='Значение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('video_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_records', to='rating.Rating', verbose_name='Суммарный рейтинг')),
            ],
            options={
                'verbose_name': 'Запись рейтинга ИВ',
                'verbose_name_plural': 'Записи рейтингов ИВ',
                'ordering': ('video_rating', 'author', 'id'),
            },
        ),
    ]
