# Generated by Django 2.1.7 on 2019-03-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingrecord',
            options={'ordering': ('rating', 'author', 'id'), 'verbose_name': 'Запись рейтинга ИВ', 'verbose_name_plural': 'Записи рейтингов ИВ'},
        ),
        migrations.RemoveField(
            model_name='ratingrecord',
            name='video_rating',
        ),
        migrations.AddField(
            model_name='ratingrecord',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rating.Rating', verbose_name='Суммарный рейтинг'),
            preserve_default=False,
        ),
    ]
