# Generated by Django 2.1.7 on 2019-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20190323_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Рейтинг интерактивного видео'),
        ),
    ]
