export const LOGIN_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';

// Centrifuge
export const CENTRIFUGO_INIT = 'CENTRIFUGO_INIT';
export const SUBSCRIBE_TO_CHANNEL = 'SUBSCRIBE_TO_CHANNEL';
export const UNSUBSCRIBE_FROM_CHANNEL = 'UNSUBSCRIBE_FROM_CHANNEL';
export const ACTIVATE_SUBSCRIPTION = 'ACTIVATE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
